baseURL = "https://w1redch4d.github.io/"
languageCode = "en-US"
title = "BloggerCh4d"
theme = "poison"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  brand = "w1redch4d"  
  description = "Fuzzing my brain till it gets SIGSEGV"
  dark_mode = true
  front_page_content = ["about", "post"]
  menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]

  github_url = "https://github.com/w1redch4d"
  x_url = "https://x.com/w1redch4d"
  remote_brand_image = "https://w1redch4d.github.io/images/avatar.jpeg"
  
  # ================================
  # 🎨 Cool Color Scheme
  # ================================

  # ▶️ Hex colors for your sidebar
  moon_sun_background_color = "#2D2A55"     # Deep violet-indigo
  moon_sun_color = "#8AFFEF"               # Neon aqua
  sidebar_a_color = "#C3F3FF"              # Soft frosty blue
  sidebar_bg_color = "#1A1B2F"             # Midnight navy
  sidebar_h1_color = "#F0F9FF"             # Light icy white-blue
  sidebar_img_border_color = "#3D3A74"     # Dimmed purple-gray
  sidebar_p_color = "#A0AEC0"              # Cool gray
  sidebar_socials_color = "#9BE8FF"        # Chill sky blue

  # ☀️ Hex colors for your content in light mode
  code_color = "#1B1F23"                   # Graphite
  code_background_color = "#D0F0FF"        # Ice blue
  code_block_color = "#151515"             # Very dark gray
  code_block_background_color = "#F0F9FF"  # Pale arctic blue
  content_bg_color = "#F9FBFD"             # White with a blue tint
  date_color = "#6D9DC5"                   # Steel blue
  link_color = "#00B8D9"                   # Bright azure
  list_color = "#4C566A"                   # Slate gray
  post_title_color = "#1F2937"             # Bold dark gray
  table_border_color = "#CCEFFF"           # Teal border
  table_stripe_color = "#E6F7FB"           # Subtle blue stripe
  text_color = "#2B2D42"                   # Rich charcoal

  # 🌘 Hex colors for your content in dark mode
  code_color_dark = "#D6F6FF"                      # Icy blue
  code_background_color_dark = "#2F3E46"           # Cool slate
  code_block_color_dark = "#F0F9FF"                # Light text
  code_block_background_color_dark = "#1E2A38"     # Dark blue-gray
  content_bg_color_dark = "#0D1117"                # Deep dark
  date_color_dark = "#6B8CA4"                      # Cool steel
  link_color_dark = "#56CCF2"                      # Luminous blue
  list_color_dark = "#B0BEC5"                      # Light gray-blue
  post_title_color_dark = "#E0F7FA"                # Glowing cyan
  table_border_color_dark = "#3A506B"              # Slate border
  table_stripe_color_dark = "#16202A"              # Very dark blue
  text_color_dark = "#CBD5E1"                      # Foggy blue

[taxonomies]
    series = 'series'
    tags = 'tags'