baseURL = "https://w1redch4d.github.io/"
languageCode = "en-US"
title = "BloggerCh4d"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "w1redch4d"
  description = "Fuzzing my brain till it gets SIGSEGV"
  github = "w1redch4d"
  linkedin = "w1redch4d"
  twitter = "w1redch4d"
  email = "weirdflexbutok200@gmail.com"
  favicon = "https://w1redch4d.github.io/images/github.png"
  avatar = "https://w1redch4d.github.io/images/avatar.jpeg"
  headerIcon = "https://w1redch4d.github.io/images/github-mark-white.png"